#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import operator
from functools import reduce 



# A slightly efficient superset of primes.
def PrimesPlus():
    yield 2
    yield 3
    i = 5
    while True:
        yield i
        if i % 6 == 1:
            i += 2
        i += 2


def GetPrimeDecomp(n):
    '''Returns a dict d with n = product p ^ d[p]'''
    d = {}
    primes = PrimesPlus()
    for p in primes:
        while n % p == 0:
            n /= p
            d[p] = d.setdefault(p, 0) + 1
        if n == 1:
            return d

def NumberOfDivisors(n):
    d = GetPrimeDecomp(n)
    powers_plus = map(lambda x: x+1, d.values())
    return reduce(operator.mul, powers_plus, 1)

def triangle(n):
    return int((n*(n+1))/2)

n = 0
incr = 1

test = NumberOfDivisors(triangle(1000))

while test <= 500:
    n += incr
    test = NumberOfDivisors(triangle(n))
    print(n)
    print(test)

print(n)
print(triangle(n))
